# Generated by Django 4.1.6 on 2023-06-17 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieTitlesFinal',
            fields=[
                ('movie_id', models.CharField(db_column='Movie_ID', max_length=20, primary_key=True, serialize=False)),
                ('number', models.IntegerField(db_column='Number')),
                ('ids', models.IntegerField(db_column='ID')),
                ('type', models.CharField(db_column='Type', max_length=20)),
                ('title', models.CharField(db_column='Title', max_length=200)),
                ('org_title', models.CharField(db_column='Org_Title', max_length=200)),
                ('adult', models.IntegerField(db_column='Adult')),
                ('start_year', models.CharField(db_column='Start_Year', max_length=11)),
                ('end_year', models.CharField(db_column='End_Year', max_length=11)),
                ('runtime', models.IntegerField(db_column='Runtime')),
                ('genres', models.CharField(db_column='Genres', max_length=100)),
            ],
            options={
                'db_table': 'movie_titles_final',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RatingsTitles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.CharField(db_column='Movie_ID', max_length=20)),
                ('user_id', models.CharField(db_column='User_ID', max_length=20)),
                ('rating', models.IntegerField(db_column='Rating')),
                ('number', models.IntegerField(db_column='Number')),
                ('type', models.CharField(db_column='Type', max_length=20)),
                ('title', models.CharField(db_column='Title', max_length=200)),
                ('org_title', models.CharField(db_column='Org_Title', max_length=200)),
                ('adult', models.IntegerField(db_column='Adult')),
                ('start_year', models.CharField(db_column='Start_Year', max_length=11)),
                ('end_year', models.CharField(db_column='End_Year', max_length=11)),
                ('runtime', models.IntegerField(db_column='Runtime')),
                ('genres', models.CharField(db_column='Genres', max_length=100)),
            ],
            options={
                'db_table': 'ratings_titles',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UsersRecommendations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_column='User_ID', max_length=20)),
                ('recommendations_svd', models.CharField(db_column='Recommendations_svd', max_length=200)),
                ('recommendations_rsvd', models.CharField(db_column='Recommendations_rsvd', max_length=200)),
                ('recommendations_nosvd', models.CharField(db_column='Recommendations_nosvd', max_length=200)),
            ],
            options={
                'db_table': 'users_recommendations',
                'managed': True,
            },
        ),
    ]
