# Generated by Django 4.1.6 on 2023-06-19 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_remove_usersrecommendations_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingstitles',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
