# Generated by Django 4.1.6 on 2023-06-19 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0004_alter_ratingstitles_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingstitles',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
